version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
      target: dev
    env_file:
      - .env
    ports:
    - 8080:8080
    volumes:
    - ./:/app
    depends_on:
      - db
    networks:
      - dev

  db:
    image: postgres:13.6-alpine3.15
    env_file:
      - .env
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - dev

networks:
  dev:
    driver: bridge
